version: "3.9"

networks:
  dev_network:

volumes:
  pgdata:

services:
  db:
    image:  postgres:14.3-alpine3.15
    container_name: diplom_db
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}" ]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      dev_network:
        aliases:
          - ${PG_HOST}      POSTGRES_DB: ${DB_NAME}


    env_file:
      - ./.env